export const SET_USERS = 'SET_USERS'
export const SET_USERS_ADVISOR = 'SET_USERS_ADVISOR'
export const SET_OPTIONS_USERS_ADVISOR = 'SET_OPTIONS_USERS_ADVISOR'
export const USER_CONECTED = 'USER_CONECTED'
export const SET_EVENTS_SUBSCRIBE = 'SET_EVENTS_SUBSCRIBE'
export const EVENTS_SUBSCRIBE_USER_CONECTED = 'EVENTS_SUBSCRIBE_USER_CONECTED'
export const EVENTS_SUBSCRIBE_USER_CONECTED_ACTIVE =
  'EVENTS_SUBSCRIBE_USER_CONECTED_ACTIVE'
export const EVENTS_SUBSCRIBE_USER_CONECTED_INACTIVE =
  'EVENTS_SUBSCRIBE_USER_CONECTED_INACTIVE'
