export const mockUser = [
  {
    id: 1,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 2,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 3,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 4,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 5,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 6,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 7,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 8,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 9,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    email: 'kalilazizsantoschami@hotmail.com',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
  {
    id: 10,
    name: 'Kalil Aziz Santos Chami',
    imageUserUrl: 'https://avatars.githubusercontent.com/u/70586283?v=4',
    college: 'PUC-GO',
    course: 'medicina',
    contact: '(64) 9 9999-9999',
    status: 'Ativo',
  },
]
